# bw.sdc — timing constraints for the AXC3000 HyperBus bandwidth-test build (SDR PHY).
#
# Clock architecture: one 25 MHz board XO -> IOPLL -> clk (50 MHz, 0deg = CK word clock) +
# clk2x (100 MHz, 0deg = SDR byte clock, exported as "clk90"). Both PLL outputs are 0deg, so there
# is only ONE clock in the Bank-3A I/O periphery (the 24403/24404 fix). The IOPLL-generated clocks and
# the JTAG-to-Avalon bridge's TCK are constrained by the Qsys IP's own generated .sdc (pulled in via
# bw_sys.qip); here we anchor the board clock, let Quartus derive the PLL outputs, add uncertainty,
# cut the async push button, and describe the HyperBus device clock.

# ---- board reference clock (25 MHz on CLK_25M_C) ----
create_clock -name CLK_25M_C -period 40.000 [get_ports CLK_25M_C]

# ---- derive the IOPLL output clocks (clk 50 MHz / clk2x 100 MHz) from the reference ----
derive_pll_clocks
derive_clock_uncertainty

# ---- HyperBus device clock hb_ck = clk2x / 2 ----
# hb_ck is generated by an ordinary fabric flop in hyperbus_phy_sdr (clocked by the 100 MHz byte
# clock, outclk1) and driven out a normal output pin — it is NOT a clock INTO the FPGA. The device
# echoes it back as RWDS, which the PHY recaptures in the 100 MHz (outclk1) domain, so no hb_ck clock
# object is needed inside the FPGA. Its off-chip (CK-to-DQ/RWDS) timing is a board-level, on-hardware
# task; the hb_ck output pin is false-pathed below with the rest of the HyperBus interface.

# ---- external HyperRAM (W957D8NB) source-synchronous I/O ----
# Full source-synchronous input/output-delay closure against the device + PCB flight time is a
# board-level, on-hardware task (read-eye calibration lives in the PHY's CAPTURE_PHASE knob). For this
# low-speed bring-up fit we cut the off-chip HyperBus data/control pins from internal timing so the
# report reflects the on-chip fabric Fmax (the two IOPLL clocks); the external interface is timed by
# hardware bring-up, not modeled here.
set_false_path -to   [get_ports {hb_dq[*] hb_rwds hb_cs_n hb_ck hb_rst_n}]
set_false_path -from [get_ports {hb_dq[*] hb_rwds}]

# ---- asynchronous, debounced-in-firmware push button: do not time it ----
set_false_path -from [get_ports USER_BTN] -to [all_registers]

# The user LEDs are slow status indicators; cut them from timing.
set_false_path -to [get_ports {LED1 RLED GLED}]

# ---- issue #13 REG_DBG / REG_PAT / REG_WRAP quasi-static knobs (default: NO extra constraint) --
# The new dbg_*/wrap_en CSR bits fan out as single-cycle clk-domain SELECT lines into the
# controller's per-state DQ/tail muxes (exactly like the cal_* read-eye knobs, which never needed a
# special constraint). They are quasi-static — the host changes them only while STATUS.busy=0 — so a
# late select cannot corrupt an in-flight burst, and they share the one `clk` domain (no CDC). Expect
# setup closure at 175 with no change here.
# FALLBACK (uncomment ONLY if the fit report shows a dbg_* SELECT path missing setup at 175):
#   set_multicycle_path -setup 2 -from [get_registers {*r_dbg*}] -to [get_registers *]
#   set_multicycle_path -hold  1 -from [get_registers {*r_dbg*}] -to [get_registers *]
# Justified by the quasi-static contract. Do NOT multicycle/false_path the DATA regs (rp_word,
# last_wr_word) — only these quasi-static SELECT lines out of r_dbg.
