// top — AXC3000 board top level for the HyperBus bandwidth test (Agilex-3 A3CY100BM16AE7S).
//
// Data path:
//   bw_sys (Qsys)                              fpga/axc3000/qsys/
//     * IOPLL: clk (50 MHz, 0deg = HyperBus CK word clock) + clk2x (100 MHz, 0deg = SDR byte clock),
//       both from the 25 MHz board XO. (The Qsys export is still named "clk90"; for the SDR PHY it
//       now carries the 100 MHz 2x byte clock — NOT a 90deg phase. See make_bw_sys.tcl.)
//     * reset controller -> synchronous active-high fabric reset (clk / 50 MHz domain)
//     * JTAG-to-Avalon-MM master bridge  --- exported Avalon-MM master (byte addressed)
//         |
//         v  (byte->word CSR adapter below)
//   hyperram_bw_test (traffic gen + scoreboard, CSR slave @ base 0x000)
//     -> hyperram_avalon (Avalon-MM slave -> ctrl -> SDR PHY)
//   (the two are wired here directly — the pure-structural rtl/bench/hyperram_bw_top.sv inlined —
//    so the av_* Avalon handshake is visible to the hyperbus_capture DEBUG module, CSR @ base 0x100)
//         |  split HyperBus device pins (hb_*_o / hb_*_oe / hb_*_i)
//         v
//   hyperbus_pads_altera (fpga/axc3000/)  = inferred tri-state I/O -> real inout board pads
//
// The measured WR_CYCLES/RD_CYCLES cover only the on-chip Avalon datapath; JTAG is control plane
// only (PLAN §8 method E compliant). Read back with sysconsole/bw_read.tcl.
//
// CLOCK PLAN (DDIO PHY, CK_SCHEME="FABRIC2X" — issue #8; ONE clock in the I/O periphery so the
// Fitter 24403/24404 two-phase blocker never applies): the frozen controller is WORD-per-clk and the
// Agilex-3 DDIO PHY (rtl/phy/hyperbus_phy_altera.sv) moves 2 bytes per clk on the two CK edges.
// clk = CK_MHZ drives the controller, the fabric, and every I/O-cell DDIO (DQ/RWDS out). hb_ck is
// generated by the PHY's FABRIC2X scheme — the silicon-proven SDR-PHY CK generator on clk2x
// (= 2x CK, 0 deg, CORE-ONLY: it clocks no I/O cell) — rising/falling edges land at T/4 / 3T/4,
// centred in both byte eyes by construction, no pin delay chain needed.
//
// Board signal names below match quartus/constraints/axc3000_board.tcl (sourced via pins.tcl).

`timescale 1ns/1ps

module top (
    // ---- board clock / reset ----
    input  wire        CLK_25M_C,   // 25 MHz fixed XO (PIN_A7, 1.2 V)
    input  wire        USER_BTN,    // S2, active-low, weak pull-up (PIN_A12, 1.2 V)

    // ---- HyperRAM (Winbond W957D8NB, single-ended x8 HyperBus, 1.2 V) ----
    inout  wire [7:0]  hb_dq,       // DQ[7:0]
    inout  wire        hb_rwds,     // RWDS
    output wire        hb_cs_n,     // chip select
    output wire        hb_ck,       // HyperBus clock (single-ended: no hb_ck_n board pin)
    output wire        hb_rst_n,    // device reset

    // ---- user LEDs (active-low, 3.3-V LVCMOS) — quick visual STATUS ----
    output wire        LED1,        // STATUS.done  (lit = done)
    output wire        RLED,        // STATUS.error (lit = error)
    output wire        GLED         // PLL locked   (lit = locked)
);

  // =========================================================================
  // Qsys backbone: clocks, reset, JTAG-Avalon master
  // =========================================================================
  wire        clk;          // CK_MHZ HyperBus CK word clock (controller + fabric + ALL I/O DDIOs)
  wire        clk2x;        // same-frequency fabric clock (0 deg) — debug capture only (legacy name)
  wire        pll_locked;
  wire        sys_rst;      // synchronous, active-high fabric reset (clk domain)

  // Exported (byte-addressed) Avalon-MM master from the JTAG bridge
  wire [31:0] m_address;
  wire [31:0] m_readdata;
  wire        m_read;
  wire        m_write;
  wire [31:0] m_writedata;
  wire        m_waitrequest;
  wire        m_readdatavalid;
  wire [3:0]  m_byteenable;

  bw_sys u_sys (
    .clk_25_clk           (CLK_25M_C),
    .reset_reset          (~USER_BTN),      // button pressed (low) => assert active-high reset
    .clk_clk              (clk),
    .clk90_clk            (clk2x),          // Qsys export "clk90" now = 100 MHz 2x byte clock (0 deg)
    .locked_export        (pll_locked),
    .sys_reset_reset      (sys_rst),
    .master_address       (m_address),
    .master_readdata      (m_readdata),
    .master_read          (m_read),
    .master_write         (m_write),
    .master_writedata     (m_writedata),
    .master_waitrequest   (m_waitrequest),
    .master_readdatavalid (m_readdatavalid),
    .master_byteenable    (m_byteenable)
  );

  // =========================================================================
  // Byte-address (JTAG master)  ->  word-address CSR slave adapter + 2-slave address decode
  //   Two CSR slaves hang off the single JTAG-Avalon master, decoded on byte-address bit [8]:
  //     m_address[8] == 0  ->  hyperram_bw_test CSR   (base 0x000, regs 0x00..0x1C)
  //     m_address[8] == 1  ->  hyperbus_capture CSR   (base 0x100, regs 0x100..0x10C)
  //   Both slaves are word-addressed (csr_address = byte_offset>>2), read combinationally, and tie
  //   waitrequest low. The JTAG-Avalon master is byte-addressed, pipelined (expects readdatavalid),
  //   and single-outstanding, so a combinational readdata/waitrequest mux on the decode bit is safe.
  // =========================================================================
  localparam int CSR_AW = 4;   // 16 bw_test regs (0x00..0x3C): STATUS/LEN/BASE/cycles/ERR + first-err diag

  wire              sel_cap        = m_address[8];    // 0x100 window = capture CSR

  // hyperram_bw_test CSR: 16 registers (0x00..0x3C) => 4 word-address bits = m_address[5:2]
  wire [CSR_AW-1:0] csr_address    = m_address[CSR_AW+1:2];
  wire              csr_read       = m_read  & ~sel_cap;
  wire              csr_write      = m_write & ~sel_cap;
  wire [31:0]       csr_writedata  = m_writedata;
  wire [31:0]       csr_readdata;
  wire              csr_waitrequest;

  // hyperbus_capture CSR: 4 registers (0x100..0x10C) => 2 word-address bits = m_address[3:2]
  wire [1:0]        cap_address    = m_address[3:2];
  wire              cap_read       = m_read  & sel_cap;
  wire              cap_write      = m_write & sel_cap;
  wire [31:0]       cap_readdata;
  wire              cap_waitrequest;

  wire [31:0] mux_readdata    = sel_cap ? cap_readdata    : csr_readdata;
  wire        mux_waitrequest = sel_cap ? cap_waitrequest : csr_waitrequest;

  assign m_waitrequest = mux_waitrequest;   // tied low inside both slaves (0 wait states)

  // Pipeline the combinational CSR read to the Avalon read-latency-1 contract the JTAG master expects:
  // capture readdata on the accept cycle, present it with readdatavalid the next cycle.
  logic [31:0] rd_hold;
  logic        rdv_q;
  always_ff @(posedge clk) begin
    if (sys_rst) begin
      rd_hold <= 32'd0;
      rdv_q   <= 1'b0;
    end else begin
      rd_hold <= mux_readdata;                       // both slaves read combinationally off the address
      rdv_q   <= m_read & ~mux_waitrequest;          // accepted this cycle (waitrequest is 0)
    end
  end
  assign m_readdata      = rd_hold;
  assign m_readdatavalid = rdv_q;

  // =========================================================================
  // LED status snoop — latch STATUS bits whenever the host polls STATUS (read of word 0).
  //   STATUS: bit0 = busy, bit1 = done, bit2 = error  (see docs/BW_TEST.md)
  //   bw_test exposes STATUS only via the CSR, so we passively observe the read bus (no 2nd master).
  // =========================================================================
  logic led_done_q, led_error_q;
  always_ff @(posedge clk) begin
    if (sys_rst) begin
      led_done_q  <= 1'b0;
      led_error_q <= 1'b0;
    end else if (csr_read && (csr_address == CSR_AW'(0))) begin
      led_done_q  <= csr_readdata[1];
      led_error_q <= csr_readdata[2];
    end
  end

  // Heartbeat blink so a freshly-flashed bitstream is visually obvious on the board (this build:
  // GLED BLINKS ~1.5 Hz while the PLL is locked, instead of the previous steady-on). Bump the toggle
  // bit / LED on each new build to tell successive flashes apart.
  logic [25:0] hb_cnt;
  always_ff @(posedge clk) begin
    if (sys_rst) hb_cnt <= '0;
    else         hb_cnt <= hb_cnt + 1'b1;
  end
  wire heartbeat = hb_cnt[25];   // SPEED build: ~1.5 Hz at 100 MHz clk (blink rate scales with CK => visible speed marker)

  assign LED1 = ~led_done_q;                 // active-low: lit when done
  assign RLED = ~led_error_q;                // active-low: lit when error
  assign GLED = ~(pll_locked & heartbeat);   // active-low: BLINKS ~1.5 Hz while PLL locked (new build marker)

  // =========================================================================
  // Bandwidth harness: bw_test (CSR + Avalon master) -> hyperram_avalon (Agilex PHY) -> split pins
  // =========================================================================
  // Split HyperBus device pins between the IP and the board pad ring.
  wire        hb_ck_int;
  wire        hb_ck_n_int;   // single-ended board: driven but not brought to a pin (DIFF_CK=0 ties it)
  wire        hb_cs_n_int;
  wire        hb_rst_n_int;
  wire [7:0]  hb_dq_o_int;
  wire        hb_dq_oe_int;
  wire [7:0]  hb_dq_i_int;
  wire        hb_rwds_o_int;
  wire        hb_rwds_oe_int;
  wire        hb_rwds_i_int;
  wire        init_done;

  // ---- bench master <-> HyperBus IP slave Avalon-MM link, hoisted to the top --------------------
  // DEBUG TAP: this inlines the pure-structural rtl/bench/hyperram_bw_top.sv (identical parameters
  // and wiring — the core modules are NOT modified) so the hyperbus_capture debug module below can
  // observe the av_* handshake alongside the HyperBus pins.
  wire [31:0] av_address;
  wire [15:0] av_burstcount;
  wire        av_read;
  wire        av_write;
  wire [15:0] av_writedata;
  wire [15:0] av_readdata;
  wire        av_readdatavalid;
  wire        av_waitrequest;
  wire [31:0] av_dbg;         // DEBUG: ctrl/front-end/FIFO taps (see hyperram_avalon dbg_bus map)

  hyperram_bw_test #(
    .DATA_WIDTH     (16),
    .ADDR_WIDTH     (32),
    .LEN_WIDTH      (16),
    .BURST_WORDS    (64),              // EXPERIMENT: larger Avalon burst — writes LEN<=64 as ONE HyperBus
                                       // burst (no write->write boundary) to confirm the boundary drop
    .CSR_ADDR_WIDTH (CSR_AW),
    .VERSION_MAGIC  (32'h4842_5754)    // "HBWT"
  ) u_bw (
    .clk             (clk),     // 50 MHz CK word clock (controller)
    .rst             (sys_rst),
    // CSR slave (word addressed) — driven by the JTAG-Avalon master through the adapter above
    .csr_address     (csr_address),
    .csr_read        (csr_read),
    .csr_readdata    (csr_readdata),
    .csr_write       (csr_write),
    .csr_writedata   (csr_writedata),
    .csr_waitrequest (csr_waitrequest),
    // Avalon-MM master -> hyperram_avalon slave (tapped by hyperbus_capture)
    .m_address       (av_address),
    .m_burstcount    (av_burstcount),
    .m_read          (av_read),
    .m_write         (av_write),
    .m_writedata     (av_writedata),
    .m_readdata      (av_readdata),
    .m_readdatavalid (av_readdatavalid),
    .m_waitrequest   (av_waitrequest)
  );

  // ---- native fe <-> ctrl channels (hyperram_avalon inlined for the GPIO-cell I/O build) ------
  wire        cmd_valid, cmd_ready, cmd_read, cmd_reg, cmd_wrap;
  wire [31:0] cmd_addr;
  wire [15:0] cmd_len;
  wire        wr_valid, wr_ready, wr_last;
  wire [15:0] wr_data;
  wire [1:0]  wr_strb;
  wire        rd_valid, rd_ready, rd_last;
  wire [15:0] rd_data;
  wire [1:0]  fe_dbg_state;
  wire [3:0]  ctrl_dbg_state;
  wire [5:0]  ctrl_dbg_rem, ctrl_dbg_seg;

  // ---- ctrl <-> board GPIO-cell I/O layer ----
  wire        phy_cs_n_w, phy_rst_n_w, phy_ck_en_w, phy_dq_oe_w, phy_rwds_oe_w, phy_rd_arm_w;
  wire [15:0] phy_dq_o_w, phy_dq_i_w;
  wire [1:0]  phy_rwds_o_w;
  wire        phy_dq_i_valid_w, phy_rwds_i_w;

  hyperbus_avalon #(
    .DQ_WIDTH   (8),
    .DATA_WIDTH (16),
    .ADDR_WIDTH (32),
    .LEN_WIDTH  (16)
  ) u_fe (
    .clk               (clk),
    .rst               (sys_rst),
    .avs_address       (av_address),
    .avs_read          (av_read),
    .avs_write         (av_write),
    .avs_writedata     (av_writedata),
    .avs_byteenable    (2'b11),
    .avs_burstcount    (av_burstcount),
    .avs_readdata      (av_readdata),
    .avs_readdatavalid (av_readdatavalid),
    .avs_waitrequest   (av_waitrequest),
    .cmd_valid         (cmd_valid),
    .cmd_ready         (cmd_ready),
    .cmd_read          (cmd_read),
    .cmd_reg           (cmd_reg),
    .cmd_wrap          (cmd_wrap),
    .cmd_addr          (cmd_addr),
    .cmd_len           (cmd_len),
    .wr_valid          (wr_valid),
    .wr_ready          (wr_ready),
    .wr_data           (wr_data),
    .wr_strb           (wr_strb),
    .wr_last           (wr_last),
    .rd_valid          (rd_valid),
    .rd_ready          (rd_ready),
    .rd_data           (rd_data),
    .rd_last           (rd_last),
    .dbg_state         (fe_dbg_state)
  );

  hyperbus_ctrl #(
    .DQ_WIDTH          (8),
    .DATA_WIDTH        (16),
    .ADDR_WIDTH        (32),
    .LEN_WIDTH         (16),
    .LATENCY_CLOCKS    (6),
    .FIXED_LATENCY     (1'b1),
    .MAX_BURST_WORDS   (0),
    .PROGRAM_CR        (1'b1),
    .POR_DELAY_CYCLES  (0),
    .INIT_CR0          (16'h8F1F),
    // Silicon findings, now first-class controller features (wave-1 ctrl-cluster):
    .BURST_BOUNDARY_WORDS (16'h2000),  // W957D8NB releases the bus when a burst crosses 16 KB
    .WR_COMMIT_READ       (1'b0),      // A/B isolation: coalescing alone (config A)
    .WR_COALESCE          (1'b1),      // issue #1 direction 4: merge contiguous writes into one CS#
    .WR_COALESCE_WAIT     (8),
    .WR_LAT_TRIM          (3)          // silicon-measured: device write window opens 3 CK early
  ) u_ctrl (
    .clk            (clk),
    .rst            (sys_rst),
    .cmd_valid      (cmd_valid),
    .cmd_ready      (cmd_ready),
    .cmd_read       (cmd_read),
    .cmd_reg        (cmd_reg),
    .cmd_wrap       (cmd_wrap),
    .cmd_addr       (cmd_addr),
    .cmd_len        (cmd_len),
    .wr_valid       (wr_valid),
    .wr_ready       (wr_ready),
    .wr_data        (wr_data),
    .wr_strb        (wr_strb),
    .wr_last        (wr_last),
    .rd_valid       (rd_valid),
    .rd_ready       (rd_ready),
    .rd_data        (rd_data),
    .rd_last        (rd_last),
    .busy           (),
    .init_done      (init_done),
    .err_underrun   (),
    .err_timeout    (),
    .phy_cs_n       (phy_cs_n_w),
    .phy_rst_n      (phy_rst_n_w),
    .phy_ck_en      (phy_ck_en_w),
    .phy_dq_o       (phy_dq_o_w),
    .phy_dq_oe      (phy_dq_oe_w),
    .phy_rwds_o     (phy_rwds_o_w),
    .phy_rwds_oe    (phy_rwds_oe_w),
    .phy_rd_arm     (phy_rd_arm_w),
    .phy_dq_i       (phy_dq_i_w),
    .phy_dq_i_valid (phy_dq_i_valid_w),
    .phy_rwds_i     (phy_rwds_i_w),
    .dbg_state      (ctrl_dbg_state),
    .dbg_rd_wptr    (ctrl_dbg_rem),
    .dbg_rd_rptr    (ctrl_dbg_seg)
  );

  // dbg_bus for the capture module — REPURPOSED as an Avalon read-stream logger (error-map debug):
  // [16] = av_readdatavalid, [15:0] = av_readdata. Each capture sample with bit16 set carries one
  // returned read word; comparing against gen_pattern gives the complete per-word error vector of
  // a small run (the ctrl-tap map it replaces is preserved in git history).
  assign av_dbg = {15'd0, av_readdatavalid, av_readdata};

  // Board I/O layer: vendor GPIO cells (DQ bidir DDR w/ delay, CK DDR out w/ CKE) + proven RWDS path.
  hyperbus_gpio_io #(
    .DQ_WIDTH         (8),
    .RD_PREAMBLE_SKIP (1),
    .TX_B_DLY         (1'b1),   // proven config (reads+zlw work); CA margin comes from CK pin delay
    .CK_DIN_HI        (1'b1),
    .CK_GEN           ("FABRIC2X")   // proven-clean CK for the bursting A/B at 175
  ) u_io (
    .clk            (clk),
    .clk_smp        (clk2x),   // VENDOR-CK build: +90deg 1x RX sampling clock (LOCAL1X)
    .rst            (sys_rst),
    .phy_cs_n       (phy_cs_n_w),
    .phy_rst_n      (phy_rst_n_w),
    .phy_ck_en      (phy_ck_en_w),
    .phy_dq_o       (phy_dq_o_w),
    .phy_dq_oe      (phy_dq_oe_w),
    .phy_rwds_o     (phy_rwds_o_w),
    .phy_rwds_oe    (phy_rwds_oe_w),
    .phy_rd_arm     (phy_rd_arm_w),
    .phy_dq_i       (phy_dq_i_w),
    .phy_dq_i_valid (phy_dq_i_valid_w),
    .phy_rwds_i     (phy_rwds_i_w),
    .hb_ck          (hb_ck),
    .hb_cs_n        (hb_cs_n),
    .hb_rst_n       (hb_rst_n),
    .hb_dq          (hb_dq),
    .hb_rwds        (hb_rwds)
  );

  // Fabric-visible probe stand-ins for the capture module (GPIO cells own the DQ pads; a raw DQ
  // fanout would re-create the P2X input-term conflict — tie those probes off).
  assign hb_ck_int      = 1'b0;
  assign hb_cs_n_int    = phy_cs_n_w;
  assign hb_rst_n_int   = phy_rst_n_w;
  assign hb_dq_o_int    = 8'h00;
  assign hb_dq_oe_int   = phy_dq_oe_w;
  assign hb_dq_i_int    = 8'h00;
  assign hb_rwds_o_int  = 1'b0;
  assign hb_rwds_oe_int = phy_rwds_oe_w;
  assign hb_rwds_i_int  = hb_rwds;

  // =========================================================================
  // On-chip logic analyzer (DEBUG): records the HyperBus pin-side signals + the av_* handshake at
  // 100 MHz from the first hb_cs_n low after arming. CSR at base 0x100 (decode above). See
  // hyperbus_capture.sv for the sample bit map and sysconsole/cap_dump.tcl for the host dump flow.
  // =========================================================================
  hyperbus_capture #(
    .DEPTH (1024)
  ) u_cap (
    .clk              (clk),
    .rst              (sys_rst),
    .cap_clk          (clk2x),
    // probes
    // DDIO PHY build: hb_ck / hb_dq_o / hb_rwds_o are tennm_ph2_ddio_out outputs that live INSIDE
    // the I/O cell — they can only drive the pad (via the OUT_DELAY_CHAIN), never core logic; a
    // fabric probe on them is unplaceable (Fitter 175006 "no routing connectivity between source
    // DDIO_OUT and the CORE_LOGIC"). Tie those three probes off; TX visibility is gone in this
    // build, but the RX side (hb_dq_i / hb_rwds_i, pad-input ibufs) and the OE / CS# / Avalon
    // handshake probes — the ones that matter for read-eye bring-up — all remain live.
    // hb_dq_i must also be tied off: the raw ibuf-to-core fanout for a probe consumes the DQ I/O
    // cell's periphery-to-core input term that the DDIO_IN's REGOUTHI/REGOUTLO need (Fitter 24403
    // "routing resource is used by"). RWDS keeps its probe — its I/O cell has no DDIO_IN (the raw
    // input already goes to the fabric delay line + level sync by design).
    .hb_cs_n          (hb_cs_n_int),
    .hb_ck            (1'b0),
    .hb_dq_oe         (hb_dq_oe_int),
    .hb_dq_o          (8'h00),
    .hb_dq_i          (hb_dq_i_int),   // legal again with FABRIC RX capture (plain fabric fanout)
    .hb_rwds_oe       (hb_rwds_oe_int),
    .hb_rwds_o        (1'b0),
    .hb_rwds_i        (hb_rwds_i_int),
    .av_read          (av_read),
    .av_write         (av_write),
    .av_waitrequest   (av_waitrequest),
    .av_readdatavalid (av_readdatavalid),
    .dbg_bus          (av_dbg),
    // CSR slave (base 0x100)
    .csr_address      (cap_address),
    .csr_read         (cap_read),
    .csr_readdata     (cap_readdata),
    .csr_write        (cap_write),
    .csr_writedata    (m_writedata),
    .csr_waitrequest  (cap_waitrequest)
  );


endmodule
