// hbgpio.v

// Generated using ACDS version 26.1 110

`timescale 1 ps / 1 ps
module hbgpio (
		input  wire        ck_cell_ck_export,      //      ck_cell_ck.export
		input  wire [1:0]  ck_cell_din_export,     //     ck_cell_din.export
		output wire [0:0]  ck_cell_pad_out_export, // ck_cell_pad_out.export
		input  wire        ck_cell_cke_export,     //     ck_cell_cke.export
		input  wire        dq_cell_ck_in_export,   //   dq_cell_ck_in.export
		input  wire        dq_cell_ck_out_export,  //  dq_cell_ck_out.export
		output wire [15:0] dq_cell_dout_export,    //    dq_cell_dout.export
		input  wire [15:0] dq_cell_din_export,     //     dq_cell_din.export
		input  wire [7:0]  dq_cell_oe_export,      //      dq_cell_oe.export
		inout  wire [7:0]  dq_cell_pad_io_export   //  dq_cell_pad_io.export
	);

	hbgpio_ck_cell ck_cell (
		.ck      (ck_cell_ck_export),      //   input,  width = 1,      ck.export
		.din     (ck_cell_din_export),     //   input,  width = 2,     din.export
		.pad_out (ck_cell_pad_out_export), //  output,  width = 1, pad_out.export
		.cke     (ck_cell_cke_export)      //   input,  width = 1,     cke.export
	);

	hbgpio_dq_cell dq_cell (
		.ck_in  (dq_cell_ck_in_export),  //   input,   width = 1,  ck_in.export
		.ck_out (dq_cell_ck_out_export), //   input,   width = 1, ck_out.export
		.dout   (dq_cell_dout_export),   //  output,  width = 16,   dout.export
		.din    (dq_cell_din_export),    //   input,  width = 16,    din.export
		.oe     (dq_cell_oe_export),     //   input,   width = 8,     oe.export
		.pad_io (dq_cell_pad_io_export)  //   inout,   width = 8, pad_io.export
	);

endmodule
